volumes:
  pg_data:
services:
  postgres:
    image: postgres:18
    container_name: "postgres"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: goledger
      POSTGRES_USER: goledger
      POSTGRES_PASSWORD: goledger
    volumes:
      - pg_data:/var/lib/postgresql
