// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package query

import (
	"context"
)

// iteratorForCreateEntries implements pgx.CopyFromSource.
type iteratorForCreateEntries struct {
	rows                 []CreateEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LedgerID,
		r.rows[0].TransactionID,
		r.rows[0].AccountID,
		r.rows[0].Amount,
	}, nil
}

func (r iteratorForCreateEntries) Err() error {
	return nil
}

func (q *Queries) CreateEntries(ctx context.Context, arg []CreateEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transaction_entry"}, []string{"ledger_id", "transaction_id", "account_id", "amount"}, &iteratorForCreateEntries{rows: arg})
}
