// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID           uuid.UUID
	LedgerID     uuid.UUID
	Currency     string
	Status       string
	Deadline     time.Time
	Metadata     json.RawMessage
	ErrorCode    *string
	ErrorMessage *string
	CreatedAt    time.Time
	ExecutedAt   pgtype.Timestamptz
}

type TransactionEntry struct {
	TransactionID uuid.UUID
	LedgerID      uuid.UUID
	AccountID     uuid.UUID
	Amount        pgtype.Int8
}
