// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package query

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateEntriesParams struct {
	LedgerID      uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        pgtype.Int8
}

const createTransaction = `-- name: CreateTransaction :one
insert into transaction(ledger_id, currency, status, deadline, metadata)
values ($1, $2, $3, $4, $5)
returning id, ledger_id, currency, status, metadata, error_code, error_message
`

type CreateTransactionParams struct {
	LedgerID uuid.UUID
	Currency string
	Status   string
	Deadline time.Time
	Metadata json.RawMessage
}

type CreateTransactionRow struct {
	ID           uuid.UUID
	LedgerID     uuid.UUID
	Currency     string
	Status       string
	Metadata     json.RawMessage
	ErrorCode    *string
	ErrorMessage *string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.LedgerID,
		arg.Currency,
		arg.Status,
		arg.Deadline,
		arg.Metadata,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Currency,
		&i.Status,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const getEntries = `-- name: GetEntries :many
select account_id, amount
from transaction_entry
where transaction_id = $2 and ledger_id = $1
`

type GetEntriesParams struct {
	LedgerID      uuid.UUID
	TransactionID uuid.UUID
}

type GetEntriesRow struct {
	AccountID uuid.UUID
	Amount    pgtype.Int8
}

func (q *Queries) GetEntries(ctx context.Context, arg GetEntriesParams) ([]GetEntriesRow, error) {
	rows, err := q.db.Query(ctx, getEntries, arg.LedgerID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesRow
	for rows.Next() {
		var i GetEntriesRow
		if err := rows.Scan(&i.AccountID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
select id, ledger_id, currency, status, metadata, error_code, error_message
from transaction
where id = $2 and ledger_id = $1
`

type GetTransactionParams struct {
	LedgerID uuid.UUID
	ID       uuid.UUID
}

type GetTransactionRow struct {
	ID           uuid.UUID
	LedgerID     uuid.UUID
	Currency     string
	Status       string
	Metadata     json.RawMessage
	ErrorCode    *string
	ErrorMessage *string
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.LedgerID, arg.ID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Currency,
		&i.Status,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}
