// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package query

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createLedger = `-- name: CreateLedger :one
insert into ledger (name, metadata)
values ($1, $2)
returning id, name, metadata
`

type CreateLedgerParams struct {
	Name     string
	Metadata json.RawMessage
}

type CreateLedgerRow struct {
	ID       uuid.UUID
	Name     string
	Metadata json.RawMessage
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) (CreateLedgerRow, error) {
	row := q.db.QueryRow(ctx, createLedger, arg.Name, arg.Metadata)
	var i CreateLedgerRow
	err := row.Scan(&i.ID, &i.Name, &i.Metadata)
	return i, err
}

const getLedger = `-- name: GetLedger :one
select id, name, metadata from ledger
where id = $1
`

type GetLedgerRow struct {
	ID       uuid.UUID
	Name     string
	Metadata json.RawMessage
}

func (q *Queries) GetLedger(ctx context.Context, id uuid.UUID) (GetLedgerRow, error) {
	row := q.db.QueryRow(ctx, getLedger, id)
	var i GetLedgerRow
	err := row.Scan(&i.ID, &i.Name, &i.Metadata)
	return i, err
}
