// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             uuid.UUID
	LedgerID       uuid.UUID
	Name           string
	Currency       string
	Metadata       json.RawMessage
	Status         string
	CreatedAt      pgtype.Timestamp
	IdempotencyKey uuid.UUID
}
