// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package query

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
insert into account (ledger_id, name, currency, overdraft_allowed, metadata, status)
values ($1, $2, $3, $4, $5, $6)
returning id, ledger_id, name, currency, balance, available_balance, overdraft_allowed, metadata, status
`

type CreateAccountParams struct {
	LedgerID         uuid.UUID
	Name             string
	Currency         string
	OverdraftAllowed bool
	Metadata         json.RawMessage
	Status           string
}

type CreateAccountRow struct {
	ID               uuid.UUID
	LedgerID         uuid.UUID
	Name             string
	Currency         string
	Balance          int64
	AvailableBalance int64
	OverdraftAllowed bool
	Metadata         json.RawMessage
	Status           string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.LedgerID,
		arg.Name,
		arg.Currency,
		arg.OverdraftAllowed,
		arg.Metadata,
		arg.Status,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.OverdraftAllowed,
		&i.Metadata,
		&i.Status,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
select id, ledger_id, name, currency, balance, available_balance, overdraft_allowed, metadata, status 
from account
where id = $2 and ledger_id = $1
`

type GetAccountParams struct {
	LedgerID uuid.UUID
	ID       uuid.UUID
}

type GetAccountRow struct {
	ID               uuid.UUID
	LedgerID         uuid.UUID
	Name             string
	Currency         string
	Balance          int64
	AvailableBalance int64
	OverdraftAllowed bool
	Metadata         json.RawMessage
	Status           string
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.LedgerID, arg.ID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Currency,
		&i.Balance,
		&i.AvailableBalance,
		&i.OverdraftAllowed,
		&i.Metadata,
		&i.Status,
	)
	return i, err
}
