// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package query

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
with inserted as (
    insert into account (ledger_id, name, currency, metadata, status, idempotency_key)
    values ($1, $2, $3, $4, $5, $6)
    on conflict (idempotency_key) do nothing
    returning id, ledger_id, name, currency, metadata, status
)
select id, ledger_id, name, currency, metadata, status from inserted
union all
select id, ledger_id, name, currency, metadata, status from account where idempotency_key = $6
`

type CreateAccountParams struct {
	LedgerID       uuid.UUID
	Name           string
	Currency       string
	Metadata       json.RawMessage
	Status         string
	IdempotencyKey uuid.UUID
}

type CreateAccountRow struct {
	ID       uuid.UUID
	LedgerID uuid.UUID
	Name     string
	Currency string
	Metadata json.RawMessage
	Status   string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.LedgerID,
		arg.Name,
		arg.Currency,
		arg.Metadata,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Currency,
		&i.Metadata,
		&i.Status,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
select id, ledger_id, name, currency, metadata, status 
from account
where id = $1
`

type GetAccountRow struct {
	ID       uuid.UUID
	LedgerID uuid.UUID
	Name     string
	Currency string
	Metadata json.RawMessage
	Status   string
}

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Name,
		&i.Currency,
		&i.Metadata,
		&i.Status,
	)
	return i, err
}
